-- ~/.config/nvim/colors/Dark.lua
vim.cmd("hi clear")
if vim.fn.exists("syntax_on") then
  vim.cmd("syntax reset")
end
vim.o.background = "dark"
vim.g.colors_name = "Dark"

-- ============================================================
-- Palette — define once, reuse everywhere
-- ============================================================
local c = {
  bg = "none", -- everything transparent by default
  fg = "#cdc9c9",
  fg_dim = "#7e7979",
  black = "#1c1c1c",
  gray1 = "#222222",
  gray2 = "#444444",
  gray3 = "#444444",
  gray4 = "#666666",
  gray5 = "#AAAAAA",
  green = "#99bbaa",
  red = "#92d8d6",
  yellow = "#fafad2",
  blue = "#cdc9c9",
  select_bg = "#3a3a3a",
  cursorline_bg = "#3a3a3a",
  -- muted background tints, only where text alone isn't legible
  green_bg = "#26311f",
  red_bg = "#352424",
  yellow_bg = "#35331f",
}

-- ============================================================
-- Helper
-- ============================================================
local function hl(group, opts)
  vim.api.nvim_set_hl(0, group, opts)
end

-- ============================================================
-- Core editor UI — all transparent by design
-- ============================================================
hl("Normal", { fg = c.fg, bg = c.bg })
hl("NormalNC", { fg = c.fg, bg = c.bg })
hl("NormalFloat", { fg = c.fg, bg = c.bg })
hl("FloatBorder", { fg = c.bg, bg = c.bg })
hl("FloatTitle", { fg = c.fg, bg = c.bg })
hl("FloatFooter", { fg = c.fg_dim, bg = c.bg })
hl("SignColumn", { bg = c.bg })
hl("FoldColumn", { fg = c.gray4, bg = c.bg })
hl("LineNr", { fg = c.gray4, bg = c.bg })
hl("CursorLineNr", { fg = c.fg, bg = c.bg, bold = true })
hl("CursorLine", { bg = "NONE" })
hl("CursorColumn", { bg = "NONE" })
hl("ColorColumn", { bg = c.gray1 })
hl("Visual", { bg = c.select_bg })
hl("VisualNOS", { bg = c.select_bg })
hl("StatusLine", { fg = c.fg, bg = c.bg })
hl("StatusLineNC", { fg = c.fg_dim, bg = c.bg })
hl("WinBar", { fg = c.fg, bg = c.bg })
hl("WinBarNC", { fg = c.fg_dim, bg = c.bg })
hl("WinSeparator", { fg = c.gray1, bg = c.bg })
hl("VertSplit", { fg = c.gray1, bg = c.bg })
hl("MsgArea", { fg = c.fg, bg = c.bg })
hl("MsgSeparator", { fg = c.gray3, bg = c.bg })
hl("EndOfBuffer", { fg = c.bg, bg = c.bg })
hl("NonText", { fg = c.gray3 })
hl("SpecialKey", { fg = c.gray3 })
hl("Whitespace", { fg = c.gray3 })
hl("Conceal", { fg = c.gray4 })
hl("Directory", { fg = c.fg })
hl("Title", { fg = c.fg, bold = true })
hl("ErrorMsg", { fg = c.red })
hl("WarningMsg", { fg = c.yellow })
hl("MoreMsg", { fg = c.fg })
hl("ModeMsg", { fg = c.fg })
hl("Question", { fg = c.fg })
hl("MatchParen", { bg = c.select_bg, bold = true })
hl("Folded", { fg = c.fg_dim, bg = c.bg })
hl("QuickFixLine", { bg = c.select_bg })
hl("WildMenu", { fg = c.fg, bg = c.select_bg })
hl("TabLine", { fg = c.fg_dim, bg = c.bg })
hl("TabLineFill", { bg = c.bg })
hl("TabLineSel", { fg = c.fg, bg = c.bg, bold = true })
hl("Cursor", { fg = c.black, bg = c.fg })
hl("lCursor", { fg = c.black, bg = c.fg })

-- Popup menu — needs *some* bg to be legible
hl("Pmenu", { fg = c.fg, bg = c.gray1 })
hl("PmenuSel", { fg = c.fg, bg = c.gray2 })
hl("PmenuSbar", { bg = c.gray2 })
hl("PmenuThumb", { bg = c.gray4 })
hl("PmenuKind", { fg = c.gray5, bg = c.gray1 })
hl("PmenuKindSel", { fg = c.gray5, bg = c.gray2 })
hl("PmenuExtra", { fg = c.fg_dim, bg = c.gray1 })
hl("PmenuExtraSel", { fg = c.fg_dim, bg = c.gray2 })
hl("PmenuMatch", { fg = c.fg, bg = c.gray1, bold = true })
hl("PmenuMatchSel", { fg = c.fg, bg = c.gray2, bold = true })
hl("ComplMatchIns", { fg = c.fg_dim })

-- Search & substitute
hl("Search", { fg = c.black, bg = c.yellow })
hl("CurSearch", { fg = c.black, bg = c.fg, bold = true })
hl("IncSearch", { fg = c.black, bg = c.fg, bold = true })
hl("Substitute", { fg = c.black, bg = c.red })

-- Spelling — undercurl only, no color noise
hl("SpellBad", { sp = c.red, undercurl = true })
hl("SpellCap", { sp = c.yellow, undercurl = true })
hl("SpellLocal", { sp = c.gray5, undercurl = true })
hl("SpellRare", { sp = c.gray5, undercurl = true })

-- ============================================================
-- Syntax highlighting — monochrome; only strings/numbers stand out
-- ============================================================
hl("Comment", { fg = c.fg_dim, italic = true })
hl("String", { fg = c.green })
hl("Character", { fg = c.green })
hl("Number", { fg = c.gray5 })
hl("Float", { fg = c.gray5 })
hl("Boolean", { fg = c.gray5 })
hl("Constant", { fg = c.gray5 })
hl("Keyword", { fg = c.fg })
hl("Statement", { fg = c.fg })
hl("Conditional", { fg = c.fg })
hl("Repeat", { fg = c.fg })
hl("Label", { fg = c.fg })
hl("Exception", { fg = c.fg })
hl("Function", { fg = c.fg })
hl("Identifier", { fg = c.fg })
hl("Type", { fg = c.fg })
hl("StorageClass", { fg = c.fg })
hl("Structure", { fg = c.fg })
hl("Typedef", { fg = c.fg })
hl("Operator", { fg = c.gray5 })
hl("Delimiter", { fg = c.gray5 })
hl("Special", { fg = c.fg })
hl("SpecialChar", { fg = c.gray5 })
hl("SpecialComment", { fg = c.fg_dim })
hl("Tag", { fg = c.fg })
hl("PreProc", { fg = c.fg })
hl("Include", { fg = c.fg })
hl("Define", { fg = c.fg })
hl("Macro", { fg = c.fg })
hl("PreCondit", { fg = c.fg })
hl("Debug", { fg = c.fg })
hl("Ignore", { fg = c.gray3 })
hl("Underlined", { underline = true })
hl("Error", { fg = c.red })
hl("Todo", { fg = c.yellow, bold = true })

-- ============================================================
-- Treesitter
-- ============================================================
hl("@variable", { fg = c.fg })
hl("@variable.builtin", { fg = c.fg, italic = true })
hl("@variable.parameter", { fg = c.fg })
hl("@variable.member", { fg = c.fg })
hl("@constant", { fg = c.gray5 })
hl("@constant.builtin", { fg = c.gray5 })
hl("@constant.macro", { fg = c.gray5 })
hl("@module", { fg = c.fg })
hl("@label", { fg = c.fg })
hl("@string", { fg = c.green })
hl("@string.documentation", { fg = c.green })
hl("@string.regexp", { fg = c.green })
hl("@string.escape", { fg = c.gray5 })
hl("@string.special", { fg = c.green })
hl("@string.special.url", { fg = c.fg_dim, underline = true })
hl("@character", { fg = c.green })
hl("@character.special", { fg = c.gray5 })
hl("@boolean", { fg = c.gray5 })
hl("@number", { fg = c.gray5 })
hl("@number.float", { fg = c.gray5 })
hl("@type", { fg = c.fg })
hl("@type.builtin", { fg = c.fg })
hl("@type.definition", { fg = c.fg })
hl("@attribute", { fg = c.gray5 })
hl("@property", { fg = c.fg })
hl("@function", { fg = c.fg })
hl("@function.builtin", { fg = c.fg })
hl("@function.call", { fg = c.fg })
hl("@function.macro", { fg = c.fg })
hl("@function.method", { fg = c.fg })
hl("@function.method.call", { fg = c.fg })
hl("@constructor", { fg = c.fg })
hl("@operator", { fg = c.gray5 })
hl("@keyword", { fg = c.fg })
hl("@keyword.coroutine", { fg = c.fg })
hl("@keyword.function", { fg = c.fg })
hl("@keyword.operator", { fg = c.fg })
hl("@keyword.import", { fg = c.fg })
hl("@keyword.repeat", { fg = c.fg })
hl("@keyword.return", { fg = c.fg })
hl("@keyword.debug", { fg = c.fg })
hl("@keyword.exception", { fg = c.fg })
hl("@keyword.conditional", { fg = c.fg })
hl("@keyword.directive", { fg = c.fg })
hl("@punctuation.delimiter", { fg = c.gray5 })
hl("@punctuation.bracket", { fg = c.gray5 })
hl("@punctuation.special", { fg = c.gray5 })
hl("@comment", { fg = c.fg_dim, italic = true })
hl("@comment.documentation", { fg = c.fg_dim, italic = true })
hl("@comment.error", { fg = c.red })
hl("@comment.warning", { fg = c.yellow })
hl("@comment.todo", { fg = c.yellow, bold = true })
hl("@comment.note", { fg = c.gray5 })
hl("@markup.strong", { bold = true })
hl("@markup.italic", { italic = true })
hl("@markup.strikethrough", { strikethrough = true })
hl("@markup.underline", { underline = true })
hl("@markup.heading", { fg = c.fg, bold = true })
hl("@markup.quote", { fg = c.fg_dim, italic = true })
hl("@markup.math", { fg = c.gray5 })
hl("@markup.link", { fg = c.fg })
hl("@markup.link.label", { fg = c.fg })
hl("@markup.link.url", { fg = c.fg_dim, underline = true })
hl("@markup.raw", { fg = c.green })
hl("@markup.list", { fg = c.gray5 })
hl("@markup.list.checked", { fg = c.green })
hl("@markup.list.unchecked", { fg = c.gray4 })
hl("@tag", { fg = c.fg })
hl("@tag.builtin", { fg = c.fg })
hl("@tag.attribute", { fg = c.gray5 })
hl("@tag.delimiter", { fg = c.gray5 })
hl("@diff.plus", { fg = c.green })
hl("@diff.minus", { fg = c.red })
hl("@diff.delta", { fg = c.yellow })
hl("@none", {})

-- LSP semantic tokens
hl("@lsp.mod.deprecated", { strikethrough = true })
hl("@lsp.type.comment", {})
hl("@lsp.type.decorator", { fg = c.gray5 })

-- ============================================================
-- LSP & diagnostics
-- ============================================================
hl("LspReferenceText", { bg = c.gray2 })
hl("LspReferenceRead", { bg = c.gray2 })
hl("LspReferenceWrite", { bg = c.gray2 })
hl("LspCodeLens", { fg = c.gray4, italic = true })
hl("LspCodeLensSeparator", { fg = c.gray3 })
hl("LspInlayHint", { fg = c.gray4, italic = true })
hl("LspSignatureActiveParameter", { bold = true })

hl("DiagnosticError", { fg = c.red })
hl("DiagnosticWarn", { fg = c.yellow })
hl("DiagnosticInfo", { fg = c.blue })
hl("DiagnosticHint", { fg = c.gray5 })
hl("DiagnosticOk", { fg = c.green })
hl("DiagnosticSignError", { fg = c.red, bg = c.bg })
hl("DiagnosticSignWarn", { fg = c.yellow, bg = c.bg })
hl("DiagnosticSignInfo", { fg = c.blue, bg = c.bg })
hl("DiagnosticSignHint", { fg = c.gray5, bg = c.bg })
hl("DiagnosticSignOk", { fg = c.green, bg = c.bg })
hl("DiagnosticVirtualTextError", { fg = c.red })
hl("DiagnosticVirtualTextWarn", { fg = c.yellow })
hl("DiagnosticVirtualTextInfo", { fg = c.blue })
hl("DiagnosticVirtualTextHint", { fg = c.gray5 })
hl("DiagnosticVirtualTextOk", { fg = c.green })
hl("DiagnosticUnderlineError", { sp = c.red, undercurl = true })
hl("DiagnosticUnderlineWarn", { sp = c.yellow, undercurl = true })
hl("DiagnosticUnderlineInfo", { sp = c.blue, undercurl = true })
hl("DiagnosticUnderlineHint", { sp = c.gray5, undercurl = true })
hl("DiagnosticUnderlineOk", { sp = c.green, undercurl = true })
hl("DiagnosticFloatingError", { fg = c.red })
hl("DiagnosticFloatingWarn", { fg = c.yellow })
hl("DiagnosticFloatingInfo", { fg = c.blue })
hl("DiagnosticFloatingHint", { fg = c.gray5 })
hl("DiagnosticFloatingOk", { fg = c.green })
hl("DiagnosticDeprecated", { sp = c.gray5, strikethrough = true })
hl("DiagnosticUnnecessary", { fg = c.fg_dim })

-- ============================================================
-- Diff & git
-- ============================================================
hl("DiffAdd", { fg = c.green, bg = c.green_bg })
hl("DiffChange", { fg = c.yellow, bg = c.yellow_bg })
hl("DiffDelete", { fg = c.red, bg = c.red_bg })
hl("DiffText", { fg = c.fg, bg = c.gray2 })
hl("diffAdded", { fg = c.green })
hl("diffRemoved", { fg = c.red })
hl("diffChanged", { fg = c.yellow })
hl("diffOldFile", { fg = c.red })
hl("diffNewFile", { fg = c.green })
hl("diffFile", { fg = c.fg })
hl("diffLine", { fg = c.fg_dim })
hl("diffIndexLine", { fg = c.gray5 })
hl("Added", { fg = c.green })
hl("Removed", { fg = c.red })
hl("Changed", { fg = c.yellow })

-- gitsigns.nvim
hl("GitSignsAdd", { fg = c.green, bg = c.bg })
hl("GitSignsChange", { fg = c.yellow, bg = c.bg })
hl("GitSignsDelete", { fg = c.red, bg = c.bg })
hl("GitSignsCurrentLineBlame", { fg = c.gray3, italic = true })

-- ============================================================
-- Completion — blink.cmp
-- ============================================================
hl("BlinkCmpMenu", { link = "Pmenu" })
hl("BlinkCmpMenuBorder", { link = "FloatBorder" })
hl("BlinkCmpMenuSelection", { link = "PmenuSel" })
hl("BlinkCmpLabel", { fg = c.fg })
hl("BlinkCmpLabelDeprecated", { fg = c.fg_dim, strikethrough = true })
hl("BlinkCmpLabelMatch", { fg = c.fg, bold = true })
hl("BlinkCmpLabelDetail", { fg = c.fg_dim })
hl("BlinkCmpLabelDescription", { fg = c.fg_dim })
hl("BlinkCmpKind", { fg = c.gray5 })
hl("BlinkCmpSource", { fg = c.fg_dim })
hl("BlinkCmpGhostText", { fg = c.gray4, italic = true })
hl("BlinkCmpDoc", { link = "NormalFloat" })
hl("BlinkCmpDocBorder", { link = "FloatBorder" })
hl("BlinkCmpDocSeparator", { link = "FloatBorder" })
hl("BlinkCmpDocCursorLine", { link = "CursorLine" })
hl("BlinkCmpSignatureHelp", { link = "NormalFloat" })
hl("BlinkCmpSignatureHelpBorder", { link = "FloatBorder" })
hl("BlinkCmpScrollBarThumb", { bg = c.gray4 })
hl("BlinkCmpScrollBarGutter", { bg = c.gray2 })

-- ============================================================
-- File explorer — neo-tree
-- ============================================================
hl("NeoTreeNormal", { fg = c.fg, bg = c.bg })
hl("NeoTreeNormalNC", { fg = c.fg, bg = c.bg })
hl("NeoTreeEndOfBuffer", { fg = c.bg, bg = c.bg })
hl("NeoTreeWinSeparator", { fg = c.gray3, bg = c.bg })
hl("NeoTreeRootName", { fg = c.fg, bold = true })
hl("NeoTreeDirectoryName", { fg = c.fg })
hl("NeoTreeDirectoryIcon", { fg = c.gray4 })
hl("NeoTreeFileName", { fg = c.fg })
hl("NeoTreeFileIcon", { fg = c.gray4 })
hl("NeoTreeFileNameOpened", { fg = c.fg, bold = true })
hl("NeoTreeIndentMarker", { fg = c.gray3 })
hl("NeoTreeExpander", { fg = c.gray4 })
hl("NeoTreeModified", { fg = c.yellow })
hl("NeoTreeGitAdded", { fg = c.green })
hl("NeoTreeGitModified", { fg = c.yellow })
hl("NeoTreeGitDeleted", { fg = c.red })
hl("NeoTreeGitStaged", { fg = c.green })
hl("NeoTreeGitUntracked", { fg = c.fg_dim })
hl("NeoTreeGitIgnored", { fg = c.gray3 })
hl("NeoTreeGitConflict", { fg = c.red, bold = true })
hl("NeoTreeDimText", { fg = c.fg_dim })
hl("NeoTreeMessage", { fg = c.fg_dim, italic = true })
hl("NeoTreeFloatBorder", { link = "FloatBorder" })
hl("NeoTreeFloatTitle", { link = "FloatTitle" })
hl("NeoTreeTitleBar", { fg = c.black, bg = c.fg })
hl("NeoTreeTabActive", { fg = c.fg, bg = c.bg, bold = true })
hl("NeoTreeTabInactive", { fg = c.fg_dim, bg = c.bg })
hl("NeoTreeTabSeparatorActive", { fg = c.bg, bg = c.bg })
hl("NeoTreeTabSeparatorInactive", { fg = c.bg, bg = c.bg })

-- ============================================================
-- UI plugins — noice, which-key, snacks
-- ============================================================
-- noice.nvim
hl("NoiceCmdline", { fg = c.fg, bg = c.bg })
hl("NoiceCmdlineIcon", { fg = c.fg })
hl("NoiceCmdlineIconSearch", { fg = c.yellow })
hl("NoiceCmdlinePrompt", { fg = c.fg, bold = true })
hl("NoiceCmdlinePopup", { fg = c.fg, bg = c.bg })
hl("NoiceCmdlinePopupBorder", { fg = c.bg, bg = c.bg })
hl("NoiceCmdlinePopupBorderSearch", { fg = c.bg, bg = c.bg })
hl("NoicePopup", { link = "NormalFloat" })
hl("NoicePopupBorder", { link = "FloatBorder" })
hl("NoicePopupmenu", { link = "Pmenu" })
hl("NoicePopupmenuBorder", { link = "FloatBorder" })
hl("NoicePopupmenuSelected", { link = "PmenuSel" })
hl("NoicePopupmenuMatch", { fg = c.fg, bold = true })
hl("NoiceMini", { fg = c.fg_dim })
hl("NoiceVirtualText", { fg = c.fg_dim })
hl("NoiceConfirm", { link = "NormalFloat" })
hl("NoiceConfirmBorder", { link = "FloatBorder" })
hl("NoiceSplit", { link = "NormalFloat" })
hl("NoiceSplitBorder", { link = "FloatBorder" })
hl("NoiceHover", { link = "NormalFloat" })
hl("NoiceHoverBorder", { link = "FloatBorder" })
hl("NoiceScrollbar", { link = "PmenuSbar" })
hl("NoiceScrollbarThumb", { link = "PmenuThumb" })
hl("NoiceFormatProgressDone", { fg = c.gray3, bg = c.gray3 })
hl("NoiceFormatProgressTodo", { fg = c.gray2, bg = c.gray2 })
hl("NoiceLspProgressClient", { fg = c.gray5 })
hl("NoiceLspProgressSpinner", { fg = c.fg })
hl("NoiceLspProgressTitle", { fg = c.fg })

-- which-key.nvim
hl("WhichKey", { fg = c.fg })
hl("WhichKeyGroup", { fg = c.gray5 })
hl("WhichKeyDesc", { fg = c.fg })
hl("WhichKeySeparator", { fg = c.gray4 })
hl("WhichKeyValue", { fg = c.fg_dim })
hl("WhichKeyNormal", { link = "NormalFloat" })
hl("WhichKeyFloat", { link = "NormalFloat" })
hl("WhichKeyBorder", { link = "FloatBorder" })
hl("WhichKeyTitle", { link = "FloatTitle" })
hl("WhichKeyIcon", { fg = c.gray5 })
hl("WhichKeyIconAzure", { fg = c.gray5 })
hl("WhichKeyIconBlue", { fg = c.gray5 })
hl("WhichKeyIconCyan", { fg = c.gray5 })
hl("WhichKeyIconGreen", { fg = c.gray5 })
hl("WhichKeyIconGrey", { fg = c.gray5 })
hl("WhichKeyIconOrange", { fg = c.gray5 })
hl("WhichKeyIconPurple", { fg = c.gray5 })
hl("WhichKeyIconRed", { fg = c.gray5 })
hl("WhichKeyIconYellow", { fg = c.gray5 })

-- snacks.nvim (picker, dashboard, notifier, indent)
hl("SnacksNormal", { link = "NormalFloat" })
hl("SnacksWinBar", { link = "WinBar" })
hl("SnacksBackdrop", { fg = c.gray3 })
hl("SnacksPicker", { fg = c.fg, bg = c.bg })
hl("SnacksPickerBorder", { fg = c.bg, bg = c.bg })
hl("SnacksPickerBoxBorder", { fg = c.bg, bg = c.bg })
hl("SnacksPickerTitle", { fg = c.fg, bg = c.bg, bold = true })
hl("SnacksPickerBoxTitle", { fg = c.fg, bg = c.bg, bold = true })
hl("SnacksPickerFooter", { fg = c.fg_dim, bg = c.bg })
hl("SnacksPickerInput", { fg = c.fg, bg = c.bg })
hl("SnacksPickerInputBorder", { fg = c.bg, bg = c.bg })
hl("SnacksPickerInputTitle", { fg = c.fg, bg = c.bg, bold = true })
hl("SnacksPickerList", { fg = c.fg, bg = c.bg })
hl("SnacksPickerListBorder", { fg = c.bg, bg = c.bg })
hl("SnacksPickerListTitle", { fg = c.fg, bg = c.bg })
hl("SnacksPickerPreview", { fg = c.fg, bg = c.bg })
hl("SnacksPickerPreviewBorder", { fg = c.bg, bg = c.bg })
hl("SnacksPickerPreviewTitle", { fg = c.fg, bg = c.bg })
hl("SnacksPickerCursorLine", { bg = c.cursorline_bg })
hl("SnacksPickerSelected", { fg = c.green })
hl("SnacksPickerMatch", { fg = c.fg, bold = true })
hl("SnacksPickerDir", { fg = c.fg_dim })
hl("SnacksPickerFile", { fg = c.fg })
hl("SnacksPickerPathHidden", { fg = c.fg_dim })
hl("SnacksPickerPathIgnored", { fg = c.gray3 })
hl("SnacksPickerGitStatus", { fg = c.gray5 })
hl("SnacksPickerGitStatusAdded", { fg = c.green })
hl("SnacksPickerGitStatusModified", { fg = c.yellow })
hl("SnacksPickerGitStatusDeleted", { fg = c.red })
hl("SnacksPickerGitStatusUntracked", { fg = c.fg_dim })
hl("SnacksPickerGitStatusIgnored", { fg = c.gray3 })
hl("SnacksPickerIcon", { fg = c.gray4 })
hl("SnacksPickerPrompt", { fg = c.fg })
hl("SnacksPickerSpinner", { fg = c.fg })
hl("SnacksPickerSearch", { fg = c.yellow })
hl("SnacksPickerToggle", { fg = c.gray5 })
hl("SnacksPickerIdx", { fg = c.fg_dim })
hl("SnacksPickerDelim", { fg = c.gray4 })
hl("SnacksPickerRow", { fg = c.fg_dim })
hl("SnacksPickerCol", { fg = c.fg_dim })
hl("SnacksPickerBufNr", { fg = c.fg_dim })
hl("SnacksPickerBufFlags", { fg = c.fg_dim })
hl("SnacksPickerKeymapRhs", { fg = c.fg_dim })
hl("SnacksPickerTime", { fg = c.fg_dim })
hl("SnacksPickerUndoCurrent", { fg = c.green })
hl("SnacksPickerUndoSaved", { fg = c.yellow })
hl("SnacksPickerManPage", { fg = c.gray5 })
hl("SnacksPickerSpecial", { fg = c.gray5 })
hl("SnacksPickerComment", { fg = c.fg_dim, italic = true })
hl("SnacksDashboardHeader", { fg = c.fg })
hl("SnacksDashboardTitle", { fg = c.fg_dim, bold = true })
hl("SnacksDashboardDesc", { fg = c.fg })
hl("SnacksDashboardIcon", { fg = c.gray4 })
hl("SnacksDashboardKey", { fg = c.gray5 })
hl("SnacksDashboardFooter", { fg = c.fg_dim, italic = true })
hl("SnacksDashboardSpecial", { fg = c.gray5 })
hl("SnacksDashboardNormal", { link = "Normal" })
hl("SnacksNotifierInfo", { fg = c.fg })
hl("SnacksNotifierWarn", { fg = c.yellow })
hl("SnacksNotifierError", { fg = c.red })
hl("SnacksNotifierDebug", { fg = c.fg_dim })
hl("SnacksNotifierTrace", { fg = c.fg_dim })
hl("SnacksNotifierTitleInfo", { fg = c.fg, bold = true })
hl("SnacksNotifierTitleWarn", { fg = c.yellow, bold = true })
hl("SnacksNotifierTitleError", { fg = c.red, bold = true })
hl("SnacksNotifierBorderInfo", { fg = c.gray4 })
hl("SnacksNotifierBorderWarn", { fg = c.yellow })
hl("SnacksNotifierBorderError", { fg = c.red })
hl("SnacksNotifierIconInfo", { fg = c.fg })
hl("SnacksNotifierIconWarn", { fg = c.yellow })
hl("SnacksNotifierIconError", { fg = c.red })
hl("SnacksIndent", { fg = c.gray2 })
hl("SnacksIndentScope", { fg = c.gray4 })
hl("SnacksIndentChunk", { fg = c.gray4 })
hl("SnacksZen", { fg = c.fg, bg = c.bg })
hl("SnacksInputNormal", { link = "NormalFloat" })
hl("SnacksInputBorder", { link = "FloatBorder" })
hl("SnacksInputTitle", { link = "FloatTitle" })
hl("SnacksInputIcon", { fg = c.gray5 })
hl("SnacksImageLoading", { fg = c.fg_dim })

-- ============================================================
-- Telescope
-- ============================================================
hl("TelescopeNormal", { fg = c.fg, bg = c.bg })
hl("TelescopeBorder", { fg = c.bg, bg = c.bg })
hl("TelescopeTitle", { fg = c.fg_dim, bold = true })
hl("TelescopePromptNormal", { fg = c.fg, bg = c.bg })
hl("TelescopePromptBorder", { fg = c.bg, bg = c.bg })
hl("TelescopePromptTitle", { fg = c.fg, bold = true })
hl("TelescopePromptPrefix", { fg = c.gray5 })
hl("TelescopePromptCounter", { fg = c.fg_dim })
hl("TelescopeResultsNormal", { fg = c.fg, bg = c.bg })
hl("TelescopeResultsBorder", { fg = c.bg, bg = c.bg })
hl("TelescopeResultsTitle", { fg = c.fg, bold = true })
hl("TelescopePreviewNormal", { fg = c.fg, bg = c.bg })
hl("TelescopePreviewBorder", { fg = c.bg, bg = c.bg })
hl("TelescopePreviewTitle", { fg = c.fg, bold = true })
hl("TelescopeSelection", { fg = c.fg, bg = c.select_bg })
hl("TelescopeSelectionCaret", { fg = c.fg, bg = c.select_bg })
hl("TelescopeMultiSelection", { fg = c.gray5 })
hl("TelescopeMultiIcon", { fg = c.gray5 })
hl("TelescopeMatching", { fg = c.yellow, bold = true })
hl("TelescopePreviewLine", { bg = c.gray2 })
hl("TelescopePreviewMatch", { fg = c.black, bg = c.yellow })

-- ============================================================
-- Motions & misc UX — flash, illuminate, yanky, todo-comments
-- ============================================================
hl("FlashBackdrop", { fg = c.fg_dim })
hl("FlashMatch", { fg = c.fg_dim })
hl("FlashCurrent", { fg = c.fg, bg = c.gray2 })
hl("FlashLabel", { fg = c.black, bg = c.yellow, bold = true })
hl("FlashPrompt", { link = "NormalFloat" })
hl("FlashPromptIcon", { fg = c.yellow })

hl("IlluminatedWordText", { bg = c.gray2 })
hl("IlluminatedWordRead", { bg = c.gray2 })
hl("IlluminatedWordWrite", { bg = c.gray2 })

hl("YankyPut", { bg = c.select_bg })
hl("YankyYanked", { bg = c.select_bg })

hl("TodoFgTODO", { fg = c.yellow, bold = true })
hl("TodoFgFIX", { fg = c.red, bold = true })
hl("TodoFgWARN", { fg = c.yellow, bold = true })
hl("TodoFgHACK", { fg = c.yellow })
hl("TodoFgNOTE", { fg = c.gray5 })
hl("TodoFgPERF", { fg = c.gray5 })
hl("TodoFgTEST", { fg = c.gray5 })
hl("TodoBgTODO", { fg = c.black, bg = c.yellow, bold = true })
hl("TodoBgFIX", { fg = c.black, bg = c.red, bold = true })
hl("TodoBgWARN", { fg = c.black, bg = c.yellow, bold = true })
hl("TodoBgNOTE", { fg = c.black, bg = c.gray5 })
hl("TodoSignTODO", { fg = c.yellow })
hl("TodoSignFIX", { fg = c.red })
hl("TodoSignWARN", { fg = c.yellow })
hl("TodoSignNOTE", { fg = c.gray5 })
hl("TodoSignPERF", { fg = c.gray5 })
hl("TodoSignTEST", { fg = c.gray5 })

-- ============================================================
-- Code navigation — treesitter-context, aerial, harpoon
-- ============================================================
hl("TreesitterContext", { bg = c.bg })
hl("TreesitterContextLineNumber", { fg = c.fg, bg = c.bg })
hl("TreesitterContextBottom", { sp = c.gray3, underline = true })
hl("TreesitterContextSeparator", { fg = c.gray3 })

hl("AerialNormal", { link = "NormalFloat" })
hl("AerialBorder", { link = "FloatBorder" })
hl("AerialLine", { bg = c.cursorline_bg })
hl("AerialGuide", { fg = c.gray3 })
hl("AerialFileIcon", { fg = c.gray5 })

hl("HarpoonWindow", { link = "NormalFloat" })
hl("HarpoonBorder", { link = "FloatBorder" })

-- ============================================================
-- Debugging — nvim-dap, dap-ui, dap-virtual-text
-- ============================================================
hl("DapBreakpoint", { fg = c.red })
hl("DapBreakpointCondition", { fg = c.yellow })
hl("DapBreakpointRejected", { fg = c.gray4 })
hl("DapLogPoint", { fg = c.gray5 })
hl("DapStopped", { fg = c.green })
hl("NvimDapVirtualText", { fg = c.fg_dim, italic = true })
hl("NvimDapVirtualTextError", { fg = c.red })
hl("NvimDapVirtualTextChanged", { fg = c.yellow })
hl("NvimDapVirtualTextInfo", { fg = c.gray5 })

hl("DapUINormal", { link = "NormalFloat" })
hl("DapUIVariable", { fg = c.fg })
hl("DapUIScope", { fg = c.fg, bold = true })
hl("DapUIType", { fg = c.gray5 })
hl("DapUIValue", { fg = c.gray5 })
hl("DapUIModifiedValue", { fg = c.yellow, bold = true })
hl("DapUIDecoration", { fg = c.gray4 })
hl("DapUIThread", { fg = c.green })
hl("DapUIStoppedThread", { fg = c.fg })
hl("DapUIFrameName", { fg = c.fg })
hl("DapUISource", { fg = c.gray5 })
hl("DapUILineNumber", { fg = c.gray5 })
hl("DapUIFloatNormal", { link = "NormalFloat" })
hl("DapUIFloatBorder", { link = "FloatBorder" })
hl("DapUIWatchesEmpty", { fg = c.fg_dim })
hl("DapUIWatchesValue", { fg = c.green })
hl("DapUIWatchesError", { fg = c.red })
hl("DapUIBreakpointsPath", { fg = c.fg })
hl("DapUIBreakpointsInfo", { fg = c.green })
hl("DapUIBreakpointsCurrentLine", { fg = c.fg, bold = true })
hl("DapUIBreakpointsLine", { fg = c.gray5 })
hl("DapUIBreakpointsDisabledLine", { fg = c.gray3 })
hl("DapUICurrentFrameName", { fg = c.green, bold = true })
hl("DapUIStepOver", { fg = c.fg })
hl("DapUIStepInto", { fg = c.fg })
hl("DapUIStepBack", { fg = c.fg })
hl("DapUIStepOut", { fg = c.fg })
hl("DapUIStop", { fg = c.red })
hl("DapUIPlayPause", { fg = c.green })
hl("DapUIRestart", { fg = c.green })
hl("DapUIUnavailable", { fg = c.gray3 })
hl("DapUIWinSelect", { fg = c.fg, bold = true })
hl("DapUIEndOfBuffer", { link = "EndOfBuffer" })

-- ============================================================
-- Testing — neotest
-- ============================================================
hl("NeotestPassed", { fg = c.green })
hl("NeotestFailed", { fg = c.red })
hl("NeotestRunning", { fg = c.yellow })
hl("NeotestSkipped", { fg = c.gray5 })
hl("NeotestTest", { fg = c.fg })
hl("NeotestNamespace", { fg = c.fg, bold = true })
hl("NeotestFile", { fg = c.fg })
hl("NeotestDir", { fg = c.fg_dim })
hl("NeotestIndent", { fg = c.gray3 })
hl("NeotestFocused", { bold = true })
hl("NeotestAdapterName", { fg = c.gray5 })
hl("NeotestExpandMarker", { fg = c.gray4 })
hl("NeotestWinSelect", { fg = c.fg, bold = true })
hl("NeotestMarked", { fg = c.yellow, bold = true })
hl("NeotestTarget", { fg = c.red })
hl("NeotestUnknown", { fg = c.fg_dim })
hl("NeotestWatching", { fg = c.yellow })
hl("NeotestBorder", { link = "FloatBorder" })

-- ============================================================
-- Lists & panels — trouble
-- ============================================================
hl("TroubleNormal", { link = "NormalFloat" })
hl("TroubleNormalNC", { link = "NormalNC" })
hl("TroubleText", { fg = c.fg })
hl("TroubleCount", { fg = c.gray5 })
hl("TroubleIndent", { fg = c.gray3 })
hl("TroubleFoldIcon", { fg = c.gray4 })
hl("TroubleFile", { fg = c.fg_dim })
hl("TroubleDirectory", { fg = c.fg_dim })
hl("TroubleLocation", { fg = c.fg_dim })
hl("TroubleCode", { fg = c.fg_dim })
hl("TroubleSource", { fg = c.fg_dim })

-- ============================================================
-- Plugin managers — lazy.nvim, mason
-- ============================================================
hl("LazyNormal", { link = "NormalFloat" })
hl("LazyH1", { fg = c.black, bg = c.fg, bold = true })
hl("LazyH2", { fg = c.fg, bold = true })
hl("LazyButton", { fg = c.fg, bg = c.gray2 })
hl("LazyButtonActive", { fg = c.fg, bg = c.gray3, bold = true })
hl("LazySpecial", { fg = c.gray5 })
hl("LazyComment", { fg = c.fg_dim, italic = true })
hl("LazyDimmed", { fg = c.fg_dim })
hl("LazyProp", { fg = c.fg_dim })
hl("LazyValue", { fg = c.gray5 })
hl("LazyUrl", { fg = c.fg_dim, underline = true })
hl("LazyDir", { fg = c.fg_dim })
hl("LazyCommit", { fg = c.green })
hl("LazyCommitIssue", { fg = c.gray5 })
hl("LazyCommitScope", { fg = c.gray5 })
hl("LazyCommitType", { fg = c.fg })
hl("LazyReasonPlugin", { fg = c.fg_dim })
hl("LazyReasonStart", { fg = c.fg_dim })
hl("LazyReasonCmd", { fg = c.fg_dim })
hl("LazyReasonKeys", { fg = c.fg_dim })
hl("LazyReasonEvent", { fg = c.fg_dim })
hl("LazyReasonFt", { fg = c.fg_dim })
hl("LazyReasonImport", { fg = c.fg_dim })
hl("LazyReasonSource", { fg = c.fg_dim })
hl("LazyReasonRuntime", { fg = c.fg_dim })
hl("LazyProgressDone", { fg = c.fg })
hl("LazyProgressTodo", { fg = c.gray3 })
hl("LazyTaskOutput", { fg = c.fg })
hl("LazyTaskError", { fg = c.red })
hl("LazyNoCond", { fg = c.yellow })
hl("LazyLocal", { fg = c.yellow })

hl("MasonNormal", { link = "NormalFloat" })
hl("MasonHeader", { fg = c.black, bg = c.fg, bold = true })
hl("MasonHeaderSecondary", { fg = c.black, bg = c.gray5, bold = true })
hl("MasonHighlight", { fg = c.fg })
hl("MasonHighlightBlock", { fg = c.black, bg = c.fg })
hl("MasonHighlightBlockBold", { fg = c.black, bg = c.fg, bold = true })
hl("MasonHighlightSecondary", { fg = c.gray5 })
hl("MasonHighlightBlockSecondary", { fg = c.black, bg = c.gray5 })
hl("MasonMuted", { fg = c.fg_dim })
hl("MasonMutedBlock", { fg = c.fg, bg = c.gray2 })
hl("MasonMutedBlockBold", { fg = c.fg, bg = c.gray2, bold = true })
hl("MasonError", { fg = c.red })
hl("MasonWarning", { fg = c.yellow })
hl("MasonHeading", { fg = c.fg, bold = true })

-- ============================================================
-- Search/replace & misc — grug-far, inc-rename
-- ============================================================
hl("GrugFarResultsMatch", { fg = c.black, bg = c.yellow })
hl("GrugFarResultsHeader", { fg = c.fg, bold = true })
hl("GrugFarResultsLineNo", { fg = c.gray4 })
hl("GrugFarResultsLineColumn", { fg = c.gray4 })
hl("GrugFarResultsPath", { fg = c.fg_dim })
hl("GrugFarInputLabel", { fg = c.fg, bold = true })

hl("IncRenameNormal", { link = "NormalFloat" })
hl("IncRenameBorder", { link = "FloatBorder" })

-- ============================================================
-- Built-in :terminal palette — grayscale + the three accents
-- ============================================================
vim.g.terminal_color_0 = c.gray1
vim.g.terminal_color_1 = c.red
vim.g.terminal_color_2 = c.green
vim.g.terminal_color_3 = c.yellow
vim.g.terminal_color_4 = c.gray5
vim.g.terminal_color_5 = c.gray5
vim.g.terminal_color_6 = c.gray5
vim.g.terminal_color_7 = c.fg
vim.g.terminal_color_8 = c.gray4
vim.g.terminal_color_9 = c.red
vim.g.terminal_color_10 = c.green
vim.g.terminal_color_11 = c.yellow
vim.g.terminal_color_12 = c.fg
vim.g.terminal_color_13 = c.fg
vim.g.terminal_color_14 = c.fg
vim.g.terminal_color_15 = "#ffffff"
